title: Edit The Web
hero_image: images/banner.png
description: edit-the-web description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Introduction
  - title: Choose a figure
  - title: The first content
  - title: Adding lists and images
  - title: Making it colourful
  - title: Using more style
  - title: Reflection
  - title: Upgrade your project
  - title: What next?
