title: edit-the-web
hero_image: images/banner.png
description: edit-the-web description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Introduction
  - title: Make a website your own
  - title: Make it fancy with CSS
  - title: What next?
